name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prebuild
      run: mkdir ./build
    - name: generate
      run: cmake ..
      working-directory: build
    - name: build
      run: cmake --build .
    - name: test
      run: ctest
    
